###
GET http://localhost:7000/posts

###
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "user1@mail.com",
  "firstName": "Hannah",
  "lastName": "Bourke",
  "password": "password123"
}

###
POST http://localhost:7000/auth/
Content-Type: application/json

{
  "email": "user1@mail.com",
  "password": "password123"
}